version: "3"
services:

  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
    - "/tmp/wordpress:/var/www/wordpress"
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    env_file: .env
    ports:
      - 9000:9000
    # depends_on:
    #   - mariadb
    volumes:
    - "/tmp/wordpress:/var/www/wordpress"
    networks:
      - inception
    restart: unless-stopped
  
  # mariadb:
  #   container_name: mariadb
  #   build: requirements/mariadb
  #   image: mariadb
  #   env_file: .env
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - inception
  #   restart: unless-stopped


networks:
  inception:
    name: inception
    driver: bridge
