version: "3"
services:

  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - "/home/$USER/data/wordpress:/var/www/html/wordpress"
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    env_file: .env
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    volumes:
      - "/home/$USER/data/wordpress:/var/www/html/wordpress"
    networks:
      - inception
    restart: unless-stopped
  
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - "/home/$USER/data/mariadb:/var/lib/mysql/wordpress"
    networks:
      - inception
    restart: unless-stopped

networks:
  inception:
    name: inception
    driver: bridge
