version: "3"
services:

  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - "wp:/var/www/html/wordpress"
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    env_file: .env
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    volumes:
      - "wp:/var/www/html/wordpress"
    networks:
      - inception
    restart: unless-stopped
  
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - "db:/var/lib/mysql"
    networks:
      - inception
    restart: unless-stopped

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wp:
    driver_opts:
      device: /home/$USER/data/wordpress
      type: none
      o: bind
  db:
    driver_opts:
      device: /home/$USER/data/mariadb
      type: none
      o: bind
