version: "3"
services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    ports:
      - 443:443
    networks:
      - inception
    restart: unless-stopped
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    env_file: .env
    ports:
      - 9000:9000
    networks:
      - inception
networks:
  inception:
    name: inception
    driver: bridge
